# This file was generated by the {rix} R package v0.16.0 on 2025-05-10
# with following call:
# >rix::rix(r_ver = "4.5.0",
#  > r_pkgs = proj_pkgs,
#  > system_pkgs = NULL,
#  > git_pkgs = proj_git_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-05-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ape
      assertr
      conflicted
      dplyr
      dwctaxon
      fs
      gitcreds
      glue
      here
      janitor
      languageserver
      MonoPhy
      purrr
      readr
      renv
      rix
      rmarkdown
      shiny
      stringr
      tarchetypes
      targets
      taxlist
      taxnames
      tibble
      tidyr
      tidyverse;
  };
 
    ftolr = (pkgs.rPackages.buildRPackage {
      name = "ftolr";
      src = pkgs.fetchgit {
        url = "https://github.com/fernphy/ftolr";
        rev = "e6f8e9b2273b3c205562b30cc769045f64113b71";
        sha256 = "sha256-4IH6L85cHRGZMNJFR1pbDMDKWbrWEGy6rXvXIVOAMbY=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          ape
          assertthat;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ ftolr rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
